services:
  - type: web
    name: rmcred
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        fromEnvVar: SECRET_KEY
      - key: EMAIL_SENHA
        fromEnvVar: EMAIL_SENHA